# conda env create -f environment-docs.yml
name: daops-docs
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  - clisops >=0.14.0,<0.15.0
  - dask
  - elasticsearch>=8.0.1
  - ipykernel
  - ipython >=8.5.0
  - matplotlib-base >=3.5.0
  - nbconvert
  - nbsphinx
  - netcdf4
  - numpy >=1.23,<2.0.0
  - pip >=25.0.0
  - roocs-utils >=0.6.4
  - sphinx >=7.1.0
  - sphinx-rtd-theme >=1.0
  - xarray >=2022.12.0,<2023.3.0
