# conda env create -f environment-docs.yml
name: daops-docs
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.13
  - clisops >=0.16.1
  - dask
  - elasticsearch>=8.0.1
  - ipykernel
  - ipython >=8.5.0
  - matplotlib-base >=3.5.0
  - nbconvert
  - nbsphinx
  - netcdf4
  - numpy >=1.24,<2.0.0
  - pip >=25.0
  - sphinx >=7.1.0,<8.2
  - sphinx-rtd-theme >=1.0
  - xarray >=2025.1.1,<2025.3.0
