# conda env create -f environment.yml
name: daops-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx
  - nbsphinx
  - ipython
  - pandoc
  - pip
  - numpy>=1.16
  - xarray>=0.15
  - dask
  - netcdf4
  - clisops>=0.6.1
  - elasticsearch>=7.9.1
  - roocs-utils>=0.2.1
  - cf-xarray>=0.4.0,<0.5.0
# - pip:
#     - roocs-utils @ git+https://github.com/roocs/roocs-utils.git@master#egg=roocs-utils
#     - clisops @ git+https://github.com/roocs/clisops.git@master#egg=clisops
